# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: CMTS API
  description: B2B Meeting Scheduling System
  version: "1.0.0"
# the domain of the service
#host: api.uber.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /login:
    get:
      summary: User Login
      description: |
       The endpoint takes user email and passwod and returns authentication token for given user credentials. The auth token is encrypted with userid information and user-role for authorization purposes.
      parameters:
        - name: username
          in: formData
          description: Email of user.
          required: true
          type: string
        - name: password
          in: formData
          description: User password.
          required: true
          type: string
      tags:
        - Login
      responses:
        200:
          description: Login using user email and password
          schema:
            $ref: '#/definitions/LoginToken'
        401:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
 
  /forgotPassword:
    get:
      summary: Forgot Password
      description: The api endpoint sends an email to useremail containing link to reset password page or security code.Once user has successfully changed pass
      tags:
        - Login
      responses:
        200:
          description: Change Password for user
          schema:
            $ref: '#/definitions/LoginToken'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
 
definitions:
  LoginToken:
    type: string
    properties:
      authToken:
        type: string
        description: Encrypted Token containing user information
 
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
